# Generated by Django 4.2 on 2025-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='student_id',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
    ]
