# Generated by Django 4.2 on 2025-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.URLField(max_length=500)),
            ],
        ),
    ]
