# Generated by Django 4.2 on 2025-06-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gallerypic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(help_text='e.g., bKash, Nagad, Bank', max_length=50)),
                ('number', models.CharField(help_text='Account number', max_length=50)),
            ],
        ),
    ]
